
services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: resume-evaluator-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${DATABASE_NAME:-resume_evaluator}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - resume-evaluator-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Resume Evaluator Application
  resume-evaluator-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: resume-evaluator-backend
    restart: unless-stopped
    ports:
      - "${API_PORT:-8000}:8000"
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
      - ./.env:/app/.env:ro
    networks:
      - resume-evaluator-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  resume-evaluator-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: resume-evaluator-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-4200}:80"
    depends_on:
      - resume-evaluator-backend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - resume-evaluator-network

volumes:
  mongodb_data:
    driver: local

networks:
  resume-evaluator-network:
    driver: bridge 